### PR TITLE
Parse and use configured IPAddress in tcp listener

### LINKED ISSUE #89: TcpPortListener does not use configured IpAddress
**Describe the bug**
The `TcpPortListener` is not using the configured ip address of the `TcpListenerConnection`. Instead the static `Any` is used.

````cs
_tcpListener = new TcpListener(new IPEndPoint(IPAddress.Any, Port));
````

### PR DESCRIPTION
**Pull request by Toxantron**
This parse the IPAddress and properly checks conflicts only for registration overlap. This allows users to use different protocols for the same port on different network adapters or IP addresses.

Closes #89.

While doing this, I noticed that part registrations are never released, even when the listener shuts down and that all connections of all modules share the same listener instance. The first might have side effects, while the other can have performance impacts due to locks. I opened #92 for this.

### CODE REVIEW

File: src/Moryx/Communication/Sockets/Server/TcpServer.cs [hunk 1]
```diff
@@ -4,37 +4,68 @@
...
-    internal static class PortMap
+    internal class PortMap
     {
         /// <summary>
         /// Application global map of ports
         /// </summary>
-        private static readonly IDictionary<int, IMessageInterpreter> Map = new Dictionary<int, IMessageInterpreter>();
+        private static readonly List<PortMap> Registrations = new List<PortMap>();
+        
+        public IPAddress Address { get; }
```
Comment (dbeuchler) [inline src/Moryx/Communication/Sockets/Server/TcpServer.cs:22]: Can you also add summaries to the new porperties?

**Review by dbeuchler — CHANGES_REQUESTED** [review]

**Review by dbeuchler — APPROVED** [review]

**Comment by Toxantron** [comment]
Thanks to @dacky179 who found this, after we didn't notice for 5 years :-D
